package main

import (
	"flag"
	"fmt"
	"path"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	defaultSingleSuffix  = "_implement.pb.go"
	defaultServicesFile  = "_implement_services.pb.go"
	defaultRPCFileSuffix = "_rpc.pb.go"
)

type layoutMode string

const (
	layoutSingle layoutMode = "single"
	layoutMulti  layoutMode = "multi"
)

type config struct {
	layout         layoutMode
	singleSuffix   string
	servicesSuffix string
	rpcSuffix      string
	implSuffix     string
	packageSuffix  string
}

func main() {
	var flagSet flag.FlagSet
	singleFile := flagSet.String("single_suffix", defaultSingleSuffix, "suffix for single-file layout")
	services := flagSet.String("services_suffix", defaultServicesFile, "suffix for service definition file in multi layout")
	rpcSuffix := flagSet.String("rpc_suffix", defaultRPCFileSuffix, "suffix for RPC files in multi layout")
	implSuffix := flagSet.String("impl_suffix", "Impl", "suffix appended to generated service struct names")
	pkgSuffix := flagSet.String("package_suffix", "", "suffix appended to go_package for generated impl package (empty = same package)")
	splitFlag := flagSet.Bool("split", false, "generate svc and rpc to separate files")

	protogen.Options{
		ParamFunc: flagSet.Set,
	}.Run(func(plugin *protogen.Plugin) error {
		cfg, err := buildConfig(*singleFile, *services, *rpcSuffix, *implSuffix, *pkgSuffix, *splitFlag)
		if err != nil {
			return err
		}

		for _, file := range plugin.Files {
			if !file.Generate || len(file.Services) == 0 {
				continue
			}

			switch cfg.layout {
			case layoutSingle:
				generateSingleFile(plugin, file, cfg)
			case layoutMulti:
				generateMultiFiles(plugin, file, cfg)
			}
		}

		return nil
	})
}

func buildConfig(single, services, rpcSuffix, impl, pkgSuffix string, split bool) (*config, error) {
	cfg := &config{
		layout:         layoutSingle,
		singleSuffix:   single,
		servicesSuffix: services,
		rpcSuffix:      rpcSuffix,
		implSuffix:     impl,
		packageSuffix:  pkgSuffix,
	}
	if split {
		cfg.layout = layoutMulti
	}
	return cfg, nil
}

func generateSingleFile(plugin *protogen.Plugin, file *protogen.File, cfg *config) {
	target := targetInfo(file, cfg)
	filename := target.prefix + cfg.singleSuffix
	g := plugin.NewGeneratedFile(filename, target.importPath)
	writeHeader(g, file)
	g.P()
	writePackage(g, target.pkgName)
	g.P()

	needsContext := false
	for _, service := range file.Services {
		for _, m := range service.Methods {
			if isUnary(m) {
				needsContext = true
				break
			}
		}
	}
	writeImports(g, file, needsContext, true, target.samePackage)
	g.P()

	for _, service := range file.Services {
		implName := service.GoName + cfg.implSuffix
		renderServiceStruct(g, service, implName)
		g.P()
		for _, method := range service.Methods {
			renderMethod(g, service, method, implName)
			g.P()
		}
	}
}

func generateMultiFiles(plugin *protogen.Plugin, file *protogen.File, cfg *config) {
	target := targetInfo(file, cfg)

	servicesFile := target.prefix + cfg.servicesSuffix
	sg := plugin.NewGeneratedFile(servicesFile, target.importPath)
	writeHeader(sg, file)
	sg.P()
	writePackage(sg, target.pkgName)
	sg.P()
	writeImports(sg, file, false, false, target.samePackage)
	sg.P()

	for _, service := range file.Services {
		implName := service.GoName + cfg.implSuffix
		renderServiceStruct(sg, service, implName)
		sg.P()

		for _, method := range service.Methods {
			rpcFile := rpcFileName(target.prefix, service.GoName, method.GoName, cfg.rpcSuffix)
			g := plugin.NewGeneratedFile(rpcFile, target.importPath)
			writeHeader(g, file)
			g.P()
			writePackage(g, target.pkgName)
			g.P()
			writeImports(g, file, isUnary(method), true, target.samePackage)
			g.P()
			renderMethod(g, service, method, implName)
			g.P()
		}
	}
}

func writeHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-go-implement. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
}

func writePackage(g *protogen.GeneratedFile, pkg protogen.GoPackageName) {
	g.P("package ", pkg)
}

func writeImports(g *protogen.GeneratedFile, file *protogen.File, needContext bool, needStatus bool, samePackage bool) {
	if samePackage && !needContext && !needStatus {
		return
	}

	g.P("import (")
	if !samePackage {
		g.P(fmt.Sprintf(". %q", string(file.GoImportPath)))
	}
	if needContext {
		g.P(`context "context"`)
	}
	if needStatus {
		g.P(`codes "google.golang.org/grpc/codes"`)
		g.P(`status "google.golang.org/grpc/status"`)
	}
	g.P(")")
}

func renderServiceStruct(g *protogen.GeneratedFile, service *protogen.Service, implName string) {
	g.P("// ", implName, " provides an empty implementation for ", service.GoName, ".")
	g.P("type ", implName, " struct {")
	g.P("\tUnimplemented", service.GoName, "Server")
	g.P("}")
	g.P()
	g.P("var _ ", service.GoName, "Server = (*", implName, ")(nil)")
}

func renderMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, implName string) {
	methodName := method.GoName
	notImplemented := fmt.Sprintf("method %s not implemented", methodName)
	streamType := fmt.Sprintf("%s_%sServer", service.GoName, methodName)

	switch {
	case isUnary(method):
		g.P("func (s *", implName, ") ", methodName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ") (*", method.Output.GoIdent.GoName, ", error) {")
		g.P("\treturn nil, status.Errorf(codes.Unimplemented, \"", notImplemented, "\")")
		g.P("}")
	case !method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
		g.P("func (s *", implName, ") ", methodName, "(req *", method.Input.GoIdent.GoName, ", stream ", streamType, ") error {")
		g.P("\treturn status.Errorf(codes.Unimplemented, \"", notImplemented, "\")")
		g.P("}")
	default:
		g.P("func (s *", implName, ") ", methodName, "(stream ", streamType, ") error {")
		g.P("\treturn status.Errorf(codes.Unimplemented, \"", notImplemented, "\")")
		g.P("}")
	}
}

func rpcFileName(prefix, service, method, suffix string) string {
	return prefix + "_" + snakeCase(service) + "_" + snakeCase(method) + suffix
}

type targetPackage struct {
	prefix      string
	importPath  protogen.GoImportPath
	pkgName     protogen.GoPackageName
	samePackage bool
}

func targetInfo(file *protogen.File, cfg *config) targetPackage {
	prefix := file.GeneratedFilenamePrefix
	importPath := file.GoImportPath
	pkgName := file.GoPackageName

	if cfg.packageSuffix != "" {
		dir, base := path.Split(prefix)
		prefix = path.Join(dir, cfg.packageSuffix, base)
		importPath = protogen.GoImportPath(path.Join(string(importPath), cfg.packageSuffix))
		pkgName = protogen.GoPackageName(path.Base(string(importPath)))
	}

	return targetPackage{
		prefix:      prefix,
		importPath:  importPath,
		pkgName:     pkgName,
		samePackage: importPath == file.GoImportPath,
	}
}

func isUnary(method *protogen.Method) bool {
	return !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer()
}

func snakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}
